# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreteReflexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Noeud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_noeud', models.CharField(choices=[('0', 'idee'), ('1', 'probleme')], max_length=1)),
                ('label', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NouveauNomNoeud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('noeud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Noeud')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('contenu', markdownx.models.MarkdownxField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('importance', models.IntegerField(default=0)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostVersionne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('contributeurs', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('noeud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Noeud')),
            ],
        ),
        migrations.CreateModel(
            name='PostVersionRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', markdownx.models.MarkdownxField()),
                ('title', models.CharField(max_length=30)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PostVersionne')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelationUserNouveauNomNoeud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouveaunom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NouveauNomNoeud')),
            ],
        ),
        migrations.CreateModel(
            name='RelationUserSuivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noeud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Noeud')),
            ],
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puissance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertinence', models.IntegerField()),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Noeud')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question_du_tag', to='app.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TypeArete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSuivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('actif', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('impact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.CharField(choices=[('0', 'admin'), ('1', 'questionneur'), ('2', 'contributeur')], default='2', max_length=1)),
                ('genre', models.CharField(choices=[('0', 'non-assigne'), ('1', 'femme'), ('2', 'homme')], default='0', max_length=1)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ban', models.BooleanField(default=False)),
                ('projetModo', models.ManyToManyField(blank=True, related_name='projetModo', to='app.Question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Post')),
                ('typeVote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TypeVote')),
                ('voteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='suggestion',
            name='userVise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Utilisateur'),
        ),
        migrations.AddField(
            model_name='reputation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Utilisateur'),
        ),
        migrations.AddField(
            model_name='relationusersuivi',
            name='type_suivi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TypeSuivi'),
        ),
        migrations.AddField(
            model_name='relationusersuivi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Utilisateur'),
        ),
        migrations.AddField(
            model_name='relationusernouveaunomnoeud',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Utilisateur'),
        ),
        migrations.AddField(
            model_name='post',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Utilisateur'),
        ),
        migrations.AddField(
            model_name='post',
            name='citations',
            field=models.ManyToManyField(blank=True, related_name='postsCites', to='app.Citation'),
        ),
        migrations.AddField(
            model_name='post',
            name='noeud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Noeud', to='app.Noeud'),
        ),
        migrations.AddField(
            model_name='post',
            name='pere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question_de_base', to='app.Question'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
        migrations.AddField(
            model_name='noeud',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questiondebase', to='app.Question'),
        ),
        migrations.AddField(
            model_name='citation',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAuteur', to='app.Utilisateur'),
        ),
        migrations.AddField(
            model_name='citation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postSource', to='app.Post'),
        ),
        migrations.AddField(
            model_name='citation',
            name='rapporteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRapporteur', to='app.Utilisateur'),
        ),
        migrations.AddField(
            model_name='aretereflexion',
            name='ideeDest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='app.Noeud'),
        ),
        migrations.AddField(
            model_name='aretereflexion',
            name='ideeSource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='app.Noeud'),
        ),
        migrations.AddField(
            model_name='aretereflexion',
            name='typeArete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TypeArete', to='app.TypeArete'),
        ),
    ]
