# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171220_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='citations',
            field=models.ManyToManyField(blank=True, related_name='postsCites', to='app.Citation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
