# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_citation_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAuteur', to='app.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='rapporteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRapporteur', to='app.Utilisateur'),
        ),
    ]
