# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180103_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationUserSuivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TypeSuivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relationusersuivi',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Post'),
        ),
        migrations.AddField(
            model_name='relationusersuivi',
            name='type_suivi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TypeSuivi'),
        ),
    ]
