# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180124_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
