# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_post_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lienpostssgraphe',
            name='typeLien',
        ),
        migrations.AddField(
            model_name='relationusersuivi',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Utilisateur'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='lienPostsSgraphe',
        ),
        migrations.DeleteModel(
            name='TypeLienSg',
        ),
    ]
