# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_post_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationusersuivi',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Utilisateur'),
            preserve_default=False,
        ),
    ]
