# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_relationusersuivi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationusersuivi',
            name='post',
        ),
        migrations.AddField(
            model_name='relationusersuivi',
            name='noeud',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Noeud'),
            preserve_default=False,
        ),
    ]
