# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_noeud_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.AddField(
            model_name='tag',
            name='question',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Question_du_tag', to='app.Question'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
