# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_typevote_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typevote',
            name='actif',
        ),
        migrations.AddField(
            model_name='typesuivi',
            name='actif',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
