# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180225_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='projetModo',
            field=models.ManyToManyField(related_name='projetModo', to='app.Question'),
        ),
    ]
