# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_utilisateur_projetmodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='genre',
            field=models.CharField(choices=[('0', 'non-assigne'), ('1', 'femme'), ('2', 'homme')], default='0', max_length=1),
        ),
    ]
