# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180314_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
