# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180325_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
