# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_utilisateur_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='projetModo',
            field=models.ManyToManyField(blank=True, null=True, related_name='projetModo', to='app.Question'),
        ),
    ]
