# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20180411_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='NouveauNomNoeud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('noeud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Noeud')),
            ],
        ),
        migrations.CreateModel(
            name='RelationUserNouveauNomNoeud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouveaunom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NouveauNomNoeud')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Utilisateur')),
            ],
        ),
    ]
