# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArreteReflexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='lienPostsSgraphe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noeud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostVersionne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertinence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeArrete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeLienSg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('impact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Post')),
                ('typeVote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TypeVote')),
                ('voteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='NoeudIdee',
            fields=[
                ('noeud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Noeud')),
            ],
            bases=('app.noeud',),
        ),
        migrations.CreateModel(
            name='NoeudPb',
            fields=[
                ('noeud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Noeud')),
            ],
            bases=('app.noeud',),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='objet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Noeud'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='userVise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='reputation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='postversionne',
            name='contributeurs',
            field=models.ManyToManyField(to='app.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='citations',
            field=models.ManyToManyField(related_name='postsCites', to='app.Citation'),
        ),
        migrations.AddField(
            model_name='post',
            name='pere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='app.Tag'),
        ),
        migrations.AddField(
            model_name='noeud',
            name='postVersionne',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.PostVersionne'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='lienpostssgraphe',
            name='typeLien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TypeLienSg'),
        ),
        migrations.AddField(
            model_name='citation',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAuteur', to='app.User'),
        ),
        migrations.AddField(
            model_name='citation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postSource', to='app.Post'),
        ),
        migrations.AddField(
            model_name='citation',
            name='rapporteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRapporteur', to='app.User'),
        ),
        migrations.AddField(
            model_name='arretereflexion',
            name='ideeDest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='app.Noeud'),
        ),
        migrations.AddField(
            model_name='arretereflexion',
            name='ideeSource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='app.Noeud'),
        ),
        migrations.AddField(
            model_name='arretereflexion',
            name='typeArrete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TypeArrete'),
        ),
    ]
