# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171214_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVersionRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', markdownx.models.MarkdownxField()),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='postversionne',
            name='contenu',
        ),
        migrations.AddField(
            model_name='postversionne',
            name='lastModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postversionrevision',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PostVersionne'),
        ),
    ]
